SET ECHO OFF
SET FEEDBACK ON
SET SERVEROUTPUT ON
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT === Connecting as IN_WPRG ===
CONNECT IN_WPRG/"InWprgPass123!"@//oracle-xe:1521/XE

PROMPT === Creating/replacing wrapper package IN_WPRG.AGAPE_API ===

CREATE OR REPLACE PACKAGE AGAPE_API AS
  PROCEDURE RECALC_SD_GLAVA(p_sd_glava_id IN NUMBER);
  PROCEDURE RECALC_SD_GLAVA_TMP(p_sd_glava_id IN NUMBER);
END AGAPE_API;
/

CREATE OR REPLACE PACKAGE BODY AGAPE_API AS

  PROCEDURE RECALC_SD_GLAVA(p_sd_glava_id IN NUMBER) IS
    l_sdg SD_GLAVA%ROWTYPE;
BEGIN
SELECT *
INTO l_sdg
FROM SD_GLAVA
WHERE ID = p_sd_glava_id
    FOR UPDATE;

ZBROJI_DOKUMENTE.ZBROJI_STA_SDG(p_sd_glava_id, l_sdg);
END;

  PROCEDURE RECALC_SD_GLAVA_TMP(p_sd_glava_id IN NUMBER) IS
    l_sdg SD_GLAVA%ROWTYPE;
BEGIN
SELECT *
INTO l_sdg
FROM SD_GLAVA
WHERE ID = p_sd_glava_id
    FOR UPDATE;

ZBROJI_DOKUMENTE.ZBROJI_STA_TMP_SDG(p_sd_glava_id, l_sdg);
END;

END AGAPE_API;
/

PROMPT === Compilation status ===
SHOW ERRORS PACKAGE AGAPE_API
SHOW ERRORS PACKAGE BODY AGAPE_API

PROMPT === USER_ERRORS (if any) ===
SELECT name, type, line, position, text
FROM user_errors
ORDER BY name, sequence;

EXIT
