-- /infra/oracle/bootstrap/ensure_in_wprg.sql
SET ECHO OFF
SET FEEDBACK ON
SET SERVEROUTPUT ON
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

DEFINE SYS_PWD = "&1"

PROMPT === Connect as SYSDBA ===
CONNECT sys/"&SYS_PWD"@//oracle-xe:1521/XE AS SYSDBA

PROMPT === Ensure DBMS_LOCK exists (install if missing; safe to run repeatedly) ===
WHENEVER SQLERROR CONTINUE
@?/rdbms/admin/dbmslock.sql
@?/rdbms/admin/prvtlock.plb
WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT === Validate SYS.DBMS_LOCK is VALID ===
DECLARE
v_cnt NUMBER;
BEGIN
SELECT COUNT(*)
INTO v_cnt
FROM dba_objects
WHERE owner = 'SYS'
  AND object_name = 'DBMS_LOCK'
  AND object_type IN ('PACKAGE', 'PACKAGE BODY')
  AND status <> 'VALID';

IF v_cnt > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'SYS.DBMS_LOCK is not VALID after install/reinstall');
END IF;
END;
/

PROMPT === Ensure application user exists + base privileges ===
DECLARE
cnt NUMBER;
BEGIN
SELECT COUNT(*)
INTO cnt
FROM dba_users
WHERE username = 'IN_WPRG';

IF cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER IN_WPRG IDENTIFIED BY "InWprgPass123!"';
END IF;
END;
/

ALTER USER IN_WPRG IDENTIFIED BY "InWprgPass123!";

GRANT CREATE SESSION   TO IN_WPRG;
GRANT CREATE TABLE     TO IN_WPRG;
GRANT CREATE VIEW      TO IN_WPRG;
GRANT CREATE SEQUENCE  TO IN_WPRG;
GRANT CREATE TRIGGER   TO IN_WPRG;
GRANT CREATE PROCEDURE TO IN_WPRG;
GRANT CREATE TYPE      TO IN_WPRG;
GRANT CREATE SYNONYM   TO IN_WPRG;

GRANT UNLIMITED TABLESPACE TO IN_WPRG;
ALTER USER IN_WPRG QUOTA UNLIMITED ON USERS;

PROMPT === Grant DBMS_LOCK execute to IN_WPRG (must be direct grant) ===
GRANT EXECUTE ON SYS.DBMS_LOCK TO IN_WPRG;

PROMPT === Quick verification as SYS ===
DECLARE
h  VARCHAR2(128);
  rc INTEGER;
BEGIN
  SYS.DBMS_LOCK.ALLOCATE_UNIQUE('AGAPE_TEST_LOCK', h);
  rc := SYS.DBMS_LOCK.REQUEST(h, 6, 1, FALSE);
  DBMS_OUTPUT.PUT_LINE('DBMS_LOCK.REQUEST rc='||rc);
  rc := SYS.DBMS_LOCK.RELEASE(h);
END;
/

EXIT
