SET ECHO OFF
SET FEEDBACK ON
SET SERVEROUTPUT ON
SET VERIFY OFF
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    DEFINE SYS_PWD = "&1"
    PROMPT === Connect as SYSDBA ===
    CONNECT sys/"&SYS_PWD"@//oracle-
xe:1521/XE AS SYSDBA

PROMPT === Ensure application user exists + base privileges ===

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM dba_users
    WHERE username = 'IN_WPRG';

    IF cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER IN_WPRG IDENTIFIED BY "InWprgPass123"';
END
IF;
END;
/

ALTER USER IN_WPRG IDENTIFIED BY "InWprgPass123";

GRANT CREATE SESSION   TO IN_WPRG;
GRANT CREATE TABLE TO IN_WPRG;
GRANT CREATE VIEW TO IN_WPRG;
GRANT CREATE SEQUENCE TO IN_WPRG;
GRANT
CREATE TRIGGER TO IN_WPRG;
GRANT CREATE PROCEDURE TO IN_WPRG;
GRANT CREATE TYPE TO IN_WPRG;
GRANT CREATE SYNONYM TO IN_WPRG;

GRANT UNLIMITED TABLESPACE TO IN_WPRG;
ALTER USER IN_WPRG QUOTA UNLIMITED ON USERS;

PROMPT === Verify IN_WPRG login ===
CONNECT IN_WPRG/"InWprgPass123"@//oracle-
xe:1521/XE

SELECT USER AS connected_user
FROM dual;

EXIT