DECLARE
  cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO cnt FROM dba_users WHERE username = 'IN_WPRG';
  IF cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER IN_WPRG IDENTIFIED BY "InWprgPass123!"';
  END IF;
END;
/

ALTER USER IN_WPRG IDENTIFIED BY "InWprgPass123!";

GRANT CREATE SESSION   TO IN_WPRG;
GRANT CREATE TABLE     TO IN_WPRG;
GRANT CREATE VIEW      TO IN_WPRG;
GRANT CREATE SEQUENCE  TO IN_WPRG;
GRANT CREATE TRIGGER   TO IN_WPRG;
GRANT CREATE PROCEDURE TO IN_WPRG;
GRANT CREATE TYPE      TO IN_WPRG;
GRANT CREATE SYNONYM   TO IN_WPRG;

GRANT UNLIMITED TABLESPACE TO IN_WPRG;
ALTER USER IN_WPRG QUOTA UNLIMITED ON USERS;
