import { StyleSheet } from "react-native";
import Colors from "@/src/constants/Colors";

export const MAX_W = 560;

export const s = StyleSheet.create({
  wrap: { flex: 1 },
  content: { width: "100%", maxWidth: MAX_W, alignSelf: "center", padding: 14, gap: 12, paddingBottom: 28 },
  card: {
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 16,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.08)",
  },
  title: { fontSize: 18, fontWeight: "900", color: Colors.text },
  sub: { color: Colors.sub, fontWeight: "700" },
  row: {
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    borderRadius: 14,
    padding: 12,
    gap: 8,
    backgroundColor: "#fff",
  },
  rowLow: { borderColor: "rgba(245,158,11,0.65)", backgroundColor: "rgba(245,158,11,0.08)" },
  rowLinked: { borderColor: "rgba(34,197,94,0.52)", backgroundColor: "rgba(34,197,94,0.07)" },
  rowNeedsQuantity: { borderColor: "rgba(245,158,11,0.58)", backgroundColor: "rgba(245,158,11,0.08)" },
  rowTop: { flexDirection: "row", gap: 8, alignItems: "flex-start", justifyContent: "space-between" },
  rowTitle: { flex: 1, fontSize: 15, fontWeight: "900", color: Colors.text },
  warning: { color: "#92400e", fontWeight: "800", fontSize: 12 },
  qtyInput: {
    height: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.12)",
    fontWeight: "900",
    color: Colors.text,
  },
  field: {
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.12)",
    fontWeight: "800",
    color: Colors.text,
  },
  dateBlock: { gap: 10 },
  dateField: {
    minHeight: 54,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.12)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  dateFieldActive: {
    borderColor: "rgba(249,115,22,0.42)",
    backgroundColor: "rgba(249,115,22,0.06)",
  },
  dateLabel: { color: Colors.sub, fontWeight: "900", fontSize: 12 },
  dateValue: { color: Colors.text, fontWeight: "900", fontSize: 15, marginTop: 2 },
  dateValueEmpty: { color: Colors.sub },
  inlineDatePicker: {
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#fff",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(15,23,42,0.10)",
  },
  dateDoneButton: {
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(15,23,42,0.10)",
    backgroundColor: "rgba(249,115,22,0.08)",
  },
  dateDoneText: { color: Colors.orange, fontWeight: "900" },
  previewWrap: {
    width: "100%",
    height: 440,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "rgba(15,23,42,0.05)",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.08)",
  },
  previewImage: { width: "100%", height: "100%" },
  previewLoading: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.72)",
  },
  previewLoadingText: { color: Colors.sub, fontWeight: "900", fontSize: 12 },
  fileName: { color: Colors.sub, fontWeight: "800", fontSize: 12 },
  partnerContext: {
    borderRadius: 14,
    padding: 12,
    gap: 3,
    backgroundColor: "rgba(59,130,246,0.08)",
    borderWidth: 1,
    borderColor: "rgba(59,130,246,0.20)",
  },
  partnerContextHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
  partnerContextLabel: { color: Colors.sharedText, fontWeight: "900", fontSize: 12 },
  partnerContextName: { color: Colors.text, fontWeight: "900", fontSize: 16, lineHeight: 21 },
  partnerContextHint: { color: Colors.sharedText, fontWeight: "800", fontSize: 12, lineHeight: 17, marginTop: 6 },
  partnerSelectButton: {
    minHeight: 38,
    borderRadius: 999,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(59,130,246,0.28)",
  },
  partnerSelectText: { color: Colors.text, fontWeight: "900", fontSize: 12 },
  contextBox: {
    borderRadius: 14,
    backgroundColor: "rgba(249,115,22,0.08)",
    borderWidth: 1,
    borderColor: "rgba(249,115,22,0.24)",
    overflow: "hidden",
  },
  contextItem: {
    padding: 12,
    gap: 5,
  },
  contextDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(249,115,22,0.22)",
  },
  selectionGrid: { gap: 10 },
  selectionCard: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: "rgba(249,115,22,0.08)",
    borderWidth: 1,
    borderColor: "rgba(249,115,22,0.24)",
    gap: 5,
  },
  selectionLabel: { color: Colors.sub, fontWeight: "900", fontSize: 12 },
  selectionValue: { color: Colors.text, fontWeight: "900", fontSize: 15, lineHeight: 20 },
  selectionAction: { color: Colors.orange, fontWeight: "900", fontSize: 12 },
  infoRow: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: "rgba(148,163,184,0.10)",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.08)",
    gap: 4,
  },
  infoLabel: { color: Colors.sub, fontWeight: "900", fontSize: 12 },
  infoValue: { color: Colors.text, fontWeight: "900" },
  confidenceLine: { flexDirection: "row", justifyContent: "space-between", gap: 8, flexWrap: "wrap" },
  analysisCard: {
    backgroundColor: "rgba(239,246,255,0.96)",
    borderColor: "rgba(59,130,246,0.24)",
  },
  analysisTop: { flexDirection: "row", alignItems: "center", gap: 10 },
  analysisTitle: { color: Colors.text, fontWeight: "900", fontSize: 16 },
  analysisText: { color: Colors.sharedText, fontWeight: "800", lineHeight: 20 },
  analysisTrack: {
    height: 8,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "rgba(59,130,246,0.12)",
  },
  analysisSweep: {
    width: 90,
    height: "100%",
    borderRadius: 999,
    backgroundColor: "rgba(37,99,235,0.74)",
  },
  assuranceHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  assurancePill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: StyleSheet.hairlineWidth,
  },
  assurancePillText: { color: Colors.text, fontWeight: "900", fontSize: 11 },
  assuranceHigh: { backgroundColor: "rgba(34,197,94,0.14)", borderColor: "rgba(34,197,94,0.45)" },
  assuranceMedium: { backgroundColor: "rgba(245,158,11,0.15)", borderColor: "rgba(245,158,11,0.45)" },
  assuranceLow: { backgroundColor: "rgba(239,68,68,0.12)", borderColor: "rgba(239,68,68,0.42)" },
  scoreRow: { flexDirection: "row", gap: 14, alignItems: "center" },
  scoreCircle: {
    width: 104,
    height: 104,
    borderRadius: 52,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(249,115,22,0.10)",
    borderWidth: 1,
    borderColor: "rgba(249,115,22,0.28)",
  },
  scoreNumber: { color: Colors.text, fontWeight: "900", fontSize: 24 },
  scoreLabel: { color: Colors.sub, fontWeight: "900", fontSize: 11 },
  scoreDetails: { flex: 1, gap: 7 },
  metricRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
  metricLabel: { color: Colors.sub, fontWeight: "800", flex: 1 },
  metricValue: { fontWeight: "900", minWidth: 24, textAlign: "right" },
  metricHigh: { color: "#15803d" },
  metricMedium: { color: "#b45309" },
  metricLow: { color: "#b91c1c" },
  pickerRow: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#fff",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pickerTitle: { color: Colors.text, fontWeight: "900" },
  pickerSub: { color: Colors.sub, fontWeight: "800", marginTop: 2 },
  actions: { flexDirection: "row", gap: 10 },
  secondary: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.06)",
  },
  secondaryText: { color: Colors.text, fontWeight: "900" },
  linkButton: {
    minHeight: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(249,115,22,0.10)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(249,115,22,0.28)",
  },
  linkButtonLinked: {
    backgroundColor: "rgba(34,197,94,0.12)",
    borderColor: "rgba(34,197,94,0.32)",
  },
  linkButtonText: { color: Colors.orange, fontWeight: "900" },
  linkButtonTextLinked: { color: "#15803d" },
  modalWrap: {
    flex: 1,
    backgroundColor: "rgba(2,6,23,0.96)",
    padding: 14,
    justifyContent: "center",
  },
  modalClose: {
    position: "absolute",
    top: 48,
    right: 18,
    zIndex: 2,
    height: 42,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseText: { color: "#fff", fontWeight: "900" },
  modalImage: { width: "100%", height: "84%" },
  pill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "rgba(15,23,42,0.06)",
  },
  pillText: { color: Colors.sub, fontWeight: "900", fontSize: 12 },
  scannerShell: {
    minHeight: 510,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "rgba(255,247,237,0.65)",
    borderWidth: 1,
    borderColor: "rgba(249,115,22,0.18)",
    padding: 10,
  },
  scannerMain: { flex: 1, minWidth: 0 },
  scannerPreview: {
    flex: 1,
    minHeight: 490,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
  },
  pdfPreview: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 16,
  },
  pdfPreviewText: { color: Colors.text, fontWeight: "900", textAlign: "center" },
  imageScanOverlay: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
    backgroundColor: "rgba(37,99,235,0.04)",
  },
  imageScanBeam: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 86,
    backgroundColor: "rgba(59,130,246,0.28)",
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: "rgba(147,197,253,0.80)",
  },
  deletePageButton: {
    position: "absolute",
    top: 12,
    left: 12,
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  replacePageActions: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    flexDirection: "row",
    gap: 8,
  },
  replacePageButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 12,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(15,23,42,0.14)",
  },
  replacePageButtonText: { color: Colors.text, fontWeight: "900", fontSize: 12 },
  emptyScanner: {
    flex: 1,
    minHeight: 490,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(249,115,22,0.38)",
    backgroundColor: "rgba(255,255,255,0.72)",
    padding: 20,
  },
  emptyScannerIcon: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(249,115,22,0.12)",
    borderWidth: 1,
    borderColor: "rgba(249,115,22,0.24)",
  },
  emptyScannerTitle: { color: Colors.text, fontWeight: "900", fontSize: 18, textAlign: "center" },
  emptyScannerText: { color: Colors.sub, fontWeight: "800", textAlign: "center", lineHeight: 20 },
  emptyScannerActions: { flexDirection: "row", gap: 10, marginTop: 4, flexWrap: "wrap", justifyContent: "center" },
  emptyScannerButton: {
    minHeight: 46,
    borderRadius: 14,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.orange,
  },
  emptyScannerPrimaryText: { color: "#fff", fontWeight: "900" },
  emptyScannerSecondaryButton: {
    minHeight: 46,
    borderRadius: 14,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(15,23,42,0.06)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(15,23,42,0.12)",
  },
  emptyScannerSecondaryText: { color: Colors.text, fontWeight: "900" },
  pageNav: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 14 },
  pageNavButton: {
    width: 56,
    height: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.94)",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
  },
  pageCountPill: {
    minHeight: 40,
    minWidth: 104,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: "rgba(249,115,22,0.10)",
    borderWidth: 1,
    borderColor: "rgba(249,115,22,0.24)",
  },
  pageCount: { color: Colors.text, fontWeight: "900", fontSize: 14 },
  thumbRail: { gap: 10, paddingVertical: 2 },
  pageThumb: {
    width: 58,
    height: 72,
    borderRadius: 12,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(148,163,184,0.14)",
    borderWidth: 2,
    borderColor: "transparent",
  },
  pageThumbActive: { borderColor: Colors.orange },
  pageThumbImage: { width: "100%", height: "100%" },
  pageThumbText: {
    position: "absolute",
    bottom: 4,
    right: 5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    overflow: "hidden",
    textAlign: "center",
    color: "#fff",
    fontWeight: "900",
    backgroundColor: "rgba(15,23,42,0.72)",
    fontSize: 11,
  },
  pageThumbAdd: {
    width: 58,
    height: 72,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(249,115,22,0.42)",
    backgroundColor: "rgba(249,115,22,0.08)",
  },
  pageThumbAddActive: { borderWidth: 2, borderColor: Colors.orange, backgroundColor: "rgba(249,115,22,0.14)" },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 10 },
  addLineButton: {
    minHeight: 38,
    borderRadius: 999,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "rgba(249,115,22,0.10)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(249,115,22,0.28)",
  },
  addLineText: { color: Colors.text, fontWeight: "900", fontSize: 12 },
  sourceText: { color: Colors.sharedText, fontWeight: "900", fontSize: 11 },
  itemActionRow: { flexDirection: "row", gap: 8, alignItems: "center" },
  deleteLineButton: {
    width: 42,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(239,68,68,0.10)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239,68,68,0.22)",
  },
});
