import { StyleSheet } from "react-native";
import Colors from "@/src/constants/Colors";

export const T = {
  page: Colors.bg,
  surface: "#FFFFFF",
  text: "#0B1220",
  subText: "#1F2A37",
  muted: "#475569",

  border: "rgba(2, 6, 23, 0.16)",
  borderStrong: "rgba(2, 6, 23, 0.22)",
  divider: "rgba(2, 6, 23, 0.12)",

  warmBadge: "#FFD3B8",
  coolBadge: "#CFE2FF",

  warmAccent: "#F97316",
  coolAccent: "#2563EB",
  neutralAccent: "#0B1220",

  heroBg: "#FFF4EC",
  heroCardBg: "rgba(255,255,255,0.72)",

  shadow: "#000000",
};

export const RIPPLE = "rgba(2,6,23,0.08)";
const H_PADDING = 16;

export const styles = StyleSheet.create({
  flex1: { flex: 1 },

  scroll: { backgroundColor: T.page },
  screenInner: { flex: 1, backgroundColor: T.page },

  content: { paddingHorizontal: H_PADDING, paddingTop: 8, paddingBottom: 4, flexGrow: 1, backgroundColor: T.page },
  sectionGap: { marginBottom: 10 },
  sectionGapStack: { marginBottom: 0, gap: 10 },

  surface: {
    borderRadius: 22,
    backgroundColor: T.surface,
    borderWidth: 1.25,
    borderColor: T.border,
    shadowColor: T.shadow,
    shadowOpacity: 0.07,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
    overflow: "hidden",
  },

  retryCard: {
    borderRadius: 18,
    borderWidth: 1.25,
    borderColor: "rgba(251,146,60,0.24)",
    backgroundColor: "#FFF7ED",
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  retryIcon: {
    width: 38,
    height: 38,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(251,146,60,0.28)",
    backgroundColor: "rgba(255,255,255,0.86)",
    alignItems: "center",
    justifyContent: "center",
  },
  retryTitle: { fontSize: 14, fontWeight: "900", color: T.text },
  retryMessage: { marginTop: 3, fontSize: 12, lineHeight: 16, fontWeight: "700", color: T.muted },

  heroWrap: { borderRadius: 20, overflow: "hidden" },
  heroBgCard: {
    borderRadius: 20,
    borderWidth: 1.25,
    borderColor: "rgba(15,23,42,0.11)",
    padding: 12,
    shadowColor: T.shadow,
    shadowOpacity: 0.09,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    overflow: "hidden",
  },
  heroBgCardExpanded: {
    minHeight: 184,
    padding: 16,
  },
  heroAccentRail: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    backgroundColor: T.warmAccent,
    opacity: 0.92,
  },

  heroTopRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 6 },
  heroTopRowExpanded: { marginBottom: 10 },
  heroAccentDot: { width: 8, height: 8, borderRadius: 999, backgroundColor: T.warmAccent },
  heroBadge: { fontSize: 11, fontWeight: "900", letterSpacing: 0.4, color: T.muted },

  heroRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  heroTitle: { marginTop: 0, fontSize: 21, fontWeight: "900", color: T.text },
  heroSubtitle: { marginTop: 4, fontSize: 12, lineHeight: 16, color: T.subText, maxWidth: 360 },
  heroTitleExpanded: { fontSize: 24 },
  heroSubtitleExpanded: { marginTop: 7, fontSize: 14, lineHeight: 20 },

  avatar: {
    width: 38,
    height: 38,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.12)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: T.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  avatarExpanded: { width: 46, height: 46, borderRadius: 18 },

  kpiRow: { marginTop: 10, flexDirection: "row", gap: 8 },
  kpiRowExpanded: { marginTop: 16, gap: 10 },
  kpiChip: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 9,
    backgroundColor: "rgba(255,255,255,0.66)",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  kpiChipExpanded: { paddingVertical: 12, paddingHorizontal: 11, borderRadius: 16 },
  kpiChipIcon: {
    width: 28,
    height: 28,
    borderRadius: 11,
    backgroundColor: "rgba(255,255,255,0.95)",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    alignItems: "center",
    justifyContent: "center",
  },
  kpiChipIconExpanded: { width: 34, height: 34, borderRadius: 13 },
  kpiChipLabel: { fontSize: 10, fontWeight: "900", color: T.muted },
  kpiChipValue: { marginTop: 1, fontSize: 12, fontWeight: "900", color: T.text },
  kpiChipLabelExpanded: { fontSize: 11 },
  kpiChipValueExpanded: { marginTop: 2, fontSize: 14 },

  fullWidthCard: { width: "100%" },

  whSurface: { borderColor: T.borderStrong },
  whRow: { padding: 16, flexDirection: "row", alignItems: "center", gap: 12 },
  whIcon: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: "#FFF2E8",
    borderWidth: 1.25,
    borderColor: "rgba(249,115,22,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  whLabel: { fontSize: 12, fontWeight: "900", color: T.muted },
  whValue: { marginTop: 3, fontSize: 15, fontWeight: "900", color: T.text },
  whRight: { alignItems: "flex-end", gap: 6 },
  whHint: { fontSize: 12, color: T.subText },

  whLoadingRow: { marginTop: 6, flexDirection: "row", alignItems: "center", gap: 8 },
  whLoadingInline: { fontSize: 12, color: T.subText },

  whDivider: { height: 1, backgroundColor: T.divider },

  whDropdown: { padding: 14, backgroundColor: "#FFFFFF" },
  whDropdownList: { gap: 10 },
  whDropdownLoading: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1.25,
    borderColor: T.borderStrong,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  whDropdownLoadingText: { fontSize: 14, color: T.subText },
  whDropdownEmpty: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1.25,
    borderColor: T.borderStrong,
    backgroundColor: "#FFFFFF",
  },
  whDropdownEmptyText: { fontSize: 14, color: T.subText, lineHeight: 20 },

  whItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1.25,
    borderColor: T.borderStrong,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
  },
  whItemIdle: {},
  whItemActive: { backgroundColor: "#FFF2E8", borderColor: "rgba(249,115,22,0.40)" },
  whItemText: { fontSize: 14, fontWeight: "900", color: T.text },

  filterBar: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    shadowColor: "rgba(15,23,42,0.10)",
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    overflow: "hidden",
  },
  filterBarExpanded: { minHeight: 118 },
  filterTopLine: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  filterTopLineExpanded: { paddingTop: 14, paddingBottom: 10 },
  filterTitleRow: { flexDirection: "row", alignItems: "center", gap: 7 },
  filterMiniIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(251,146,60,0.42)",
    backgroundColor: "rgba(251,146,60,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  filterTitle: { fontSize: 14, fontWeight: "900", color: T.text },
  filterSelectRow: {
    paddingHorizontal: 10,
    paddingBottom: 8,
    flexDirection: "row",
    gap: 6,
  },
  filterSelectRowExpanded: { paddingBottom: 8 },
  filterSelect: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.11)",
    backgroundColor: "rgba(255,255,255,0.74)",
    paddingHorizontal: 7,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  filterSelectExpanded: { minHeight: 50, paddingVertical: 6, borderRadius: 14 },
  filterSelectOpen: {
    backgroundColor: "rgba(255,236,220,0.76)",
    borderColor: "rgba(251,146,60,0.46)",
  },
  filterSelectIcon: {
    width: 24,
    height: 24,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
  },
  filterSelectIconOpen: {
    borderColor: "rgba(251,146,60,0.35)",
    backgroundColor: "rgba(251,146,60,0.14)",
  },
  filterSelectLabel: { fontSize: 9, fontWeight: "800", color: "rgba(15,23,42,0.62)" },
  filterSelectLabelOpen: { color: T.text },
  filterSelectValue: { marginTop: 1, fontSize: 11, lineHeight: 14, fontWeight: "900", color: T.text },
  filterSelectLabelExpanded: { fontSize: 9 },
  filterSelectValueExpanded: { fontSize: 11, lineHeight: 14 },
  filterSummary: {
    marginHorizontal: 10,
    marginBottom: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(251,146,60,0.22)",
    backgroundColor: "rgba(255,255,255,0.62)",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  filterSummaryLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: "rgba(15,23,42,0.52)",
  },
  filterSummaryText: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    color: T.text,
  },
  filterDropdown: {
    borderTopWidth: 1,
    borderTopColor: "rgba(15,23,42,0.08)",
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 10,
    backgroundColor: "rgba(255,255,255,0.72)",
  },
  dropdownOptionWrap: {
    borderRadius: 14,
    overflow: "hidden",
  },
  dropdownOption: {
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownOptionActive: { backgroundColor: "rgba(251,146,60,0.10)" },
  dropdownOptionPressed: { backgroundColor: "rgba(15,23,42,0.07)" },
  dropdownOptionText: { flex: 1, fontSize: 14, lineHeight: 18, fontWeight: "800", color: T.text },
  dropdownOptionTextActive: { color: T.text },
  dropdownCheckPill: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: "rgba(251,146,60,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  dropdownCheckGhost: { width: 28, height: 28 },

  pressed: { opacity: 0.97 },

  statusRail: {
    minHeight: 68,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    flexDirection: "row",
    shadowColor: "rgba(15,23,42,0.10)",
    shadowOpacity: 1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 9 },
    elevation: 3,
    overflow: "hidden",
  },
  statusRailExpanded: { minHeight: 98 },
  statusItem: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    position: "relative",
  },
  statusItemExpanded: { paddingVertical: 14, paddingHorizontal: 12 },
  statusIcon: {
    width: 30,
    height: 30,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    alignItems: "center",
    justifyContent: "center",
  },
  statusIconExpanded: { width: 36, height: 36, borderRadius: 13 },
  statusIconNeutral: { backgroundColor: "rgba(15,23,42,0.04)" },
  statusIconWarm: { backgroundColor: "rgba(251,146,60,0.12)", borderColor: "rgba(251,146,60,0.32)" },
  statusIconCool: { backgroundColor: "rgba(37,99,235,0.10)", borderColor: "rgba(37,99,235,0.25)" },
  statusValue: { fontSize: 16, lineHeight: 19, fontWeight: "900", color: T.text },
  statusLabel: { marginTop: 1, fontSize: 10, fontWeight: "800", color: T.muted },
  statusValueExpanded: { fontSize: 18, lineHeight: 22 },
  statusLabelExpanded: { marginTop: 3, fontSize: 11 },
  statusDivider: {
    position: "absolute",
    right: 0,
    top: 12,
    bottom: 12,
    width: 1,
    backgroundColor: "rgba(15,23,42,0.08)",
  },

  accSurface: {
    borderColor: "rgba(15,23,42,0.11)",
    borderRadius: 20,
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  accHeaderGradient: { overflow: "hidden" },
  accHeader: { padding: 14, flexDirection: "row", alignItems: "center", gap: 12 },

  accIcon: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
  },
  accIconWarm: { backgroundColor: "rgba(251,146,60,0.16)", borderColor: "rgba(251,146,60,0.34)" },
  accIconCool: { backgroundColor: "rgba(37,99,235,0.12)", borderColor: "rgba(37,99,235,0.28)" },

  accTitle: { fontSize: 15, fontWeight: "900", color: T.text },
  accSub: { marginTop: 3, fontSize: 12, color: "rgba(15,23,42,0.78)" },

  accRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  countPill: {
    minWidth: 54,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    alignItems: "center",
    justifyContent: "center",
  },
  countPillText: { fontSize: 12, fontWeight: "900", color: "#000000" },

  accDivider: { height: 0, backgroundColor: T.divider },
  accBody: { paddingHorizontal: 14, paddingBottom: 14, paddingTop: 14, backgroundColor: "#FFFFFF" },

  listCard: {
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.25,
    borderColor: T.borderStrong,
    overflow: "hidden",
  },

  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "flex-start",
  },
  rowDivider: { borderBottomWidth: 1, borderBottomColor: T.divider },
  rowLeft: { flex: 1 },
  rowName: { fontSize: 13, lineHeight: 17, fontWeight: "900", color: T.text },
  rowCode: { marginTop: 3, fontSize: 11, color: T.muted },

  rowRight: { alignItems: "flex-end" },
  qtyBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, borderWidth: 1.25, borderColor: "rgba(2,6,23,0.22)" },
  qtyWarm: { backgroundColor: T.warmBadge },
  qtyCool: { backgroundColor: T.coolBadge },
  qtyText: { fontSize: 11, fontWeight: "900", color: T.text },
  rowHint: { marginTop: 4, fontSize: 11, color: T.subText },

  empty: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1.25,
    borderColor: T.borderStrong,
  },
  emptyText: { fontSize: 14, color: T.subText, lineHeight: 20 },
});
