package hr.agape.document.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.OffsetDateTime;

/**
 * Domain model for SD_GLAVA (document header).
 * <p>
 * One row = one commercial document (e.g., dispatch note / OTPREMNICA).
 * Line items are stored in SD_STAVKE and reference this header via {@link #id}.
 * Most IDs and auto-numbering are handled by Oracle sequences/triggers:
 * <ul>
 *   <li>SD_GLAVA_SEQ → populates {@link #id}</li>
 *   <li>SD_GLAVA_BIU → auto-increments {@link #documentNumber} per {@link #documentId},
 *       normalizes dates, etc.</li>
 * </ul>
 * </p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentHeaderEntity {
    /**
     * Primary key of SD_GLAVA (generated by SD_GLAVA_SEQ).
     * Column: SD_GLAVA.ID
     */
    private Long id;

    /**
     * Logical document slot used by the warehouse (e.g. 3, 9, 23, 32).
     * Column: SD_GLAVA.DOKUMENT_ID
     * <p>Maps to a row in SD_SIFREG → SD_SIFREZ that defines the business type
     * (e.g. DOKUMENTID=OTPREMNICA, NAZIVDOKUMENTA=IZDATNICA) and stock-change rules.</p>
     */
    private Long documentId;

    /**
     * Sequential number within a given {@link #documentId}.
     * Column: SD_GLAVA.DOKUMENTBR
     * <p>Assigned by trigger SD_GLAVA_BIU if not provided.</p>
     */
    private Long documentNumber;

    /**
     * Business date of the document.
     * Column: SD_GLAVA.DATUM_DOKUMENTA
     * <p>Set by trigger if omitted.</p>
     */
    private LocalDate documentDate;

    /**
     * Recipient/partner for whom the goods are dispatched.
     * Column: SD_GLAVA.PARTNER_ID (FK → PARTNERI.PARTNER_ID)
     */
    private Long partnerId;

    /**
     * User/employee who created the document.
     *
     * <p>Column: {@code SD_GLAVA.IZRADIO} (NOT NULL). Typically, stores the application user ID
     * or employee ID that performed the booking.</p>
     */
    private Long createdBy;

    private OffsetDateTime createdAt;
}
